# Generated by Django 5.2.7 on 2025-11-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_contactpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
